### PR TITLE
Decode a Morse code message

### PR DESCRIPTION
**Pull request by batoorsohail**
### In this project we:

- [x] Created a method to decode a Morse code character, take a string parameter, and return the corresponding character in uppercase
- [x] Created a method to decode an entire word in Morse code, take a string parameter, and return the string representation. A single space will separate every character in a word
- [x] Create a method to decode the message in Morse code, take a string parameter, and return the string representation. 3 spaces will separate every word

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Kindly ensure that your ReadMe is professionally documented:
  * Kindly ensure to the _Future Features_ section to your ReadMe, which should include 1-3 potential features to be added later. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rloterh** [comment]
@batoorsohail 
Your MIT License is broken, kindly fix it asap!

**Comment by batoorsohail** [comment]
Thanks, @rloterh 🙌 
I fixed the link to the MIT License. 😃

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Yemi & Sohail,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
- Decoding functions properly added!
 
Cheers..Happy coding! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
